// SPDX-License-Identifier: GPL-2.0
// TC ingress filter: protect only TCP/22 RST packets without the guard option.
#include <linux/bpf.h>
#include <linux/if_ether.h>
#include <linux/if_vlan.h>
#include <linux/ip.h>
#include <linux/ipv6.h>
#include <linux/in.h>
#include <linux/tcp.h>
#include <bpf/bpf_helpers.h>

#define SSH_PORT 22
#define TCP_OPT_EXPERIMENTAL 254
#define RST_GUARD_OPTION_LEN 10
#define TC_ACT_OK 0
#define TC_ACT_SHOT 2
#define BPF_HTONS(x) ((__u16)__builtin_bswap16((__u16)(x)))

struct vlan_header {
	__u16 tci;
	__u16 encapsulated_proto;
} __attribute__((packed));

static const __u8 rst_guard_magic[8] = {
	0x52, 0x53, 0x54, 0x47, 0x55, 0x41, 0x52, 0x44,
};

static __always_inline int has_guard_option(const __u8 *options, __u32 length)
{
	__u32 off = 0;

	/* The option must be the final option, not merely present somewhere. */
#pragma unroll
	for (int i = 0; i < 40; i++) {
		__u8 kind;
		__u8 option_len;

		if (off >= length)
			break;
		if (off + 1 > length)
			break;

		kind = options[off];
		if (kind == 0)
			return 0; /* EOL is the final option, so guard was absent. */
		if (kind == 1) {
			off++;
			continue;
		}
		if (off + 2 > length)
			break;
		option_len = options[off + 1];
		if (option_len < 2 || off + option_len > length)
			break;
		if (kind == TCP_OPT_EXPERIMENTAL &&
			option_len == RST_GUARD_OPTION_LEN) {
			int matches = 1;
			/* TCP options are 32-bit aligned; accept only EOL zero padding. */
			for (int k = off + option_len; k < length; k++)
				if (options[k] != 0)
					matches = 0;
			for (int j = 0; j < 8; j++)
				if (options[off + 2 + j] != rst_guard_magic[j])
					matches = 0;
			return matches;
		}
		off += option_len;
	}
	return 0;
}

static __always_inline int check_tcp(void *data, void *data_end,
					     __u32 offset)
{
	struct tcphdr *tcp = data + offset;
		__u32 header_len;
		__u32 option_len;
		__u8 *options;

	if ((void *)(tcp + 1) > data_end)
		return TC_ACT_OK;
	if (tcp->source != BPF_HTONS(SSH_PORT) &&
		tcp->dest != BPF_HTONS(SSH_PORT))
		return TC_ACT_OK;
	if (!tcp->rst)
		return TC_ACT_OK;

	header_len = (__u32)tcp->doff * 4;
	if (header_len < sizeof(*tcp) || data + offset + header_len > data_end)
		return TC_ACT_OK;
	option_len = header_len - sizeof(*tcp);
	options = (__u8 *)tcp + sizeof(*tcp);
	/* Keep this check adjacent to the pointer passed to the parser. Older
	 * verifiers do not infer this range from the complete TCP-header check. */
	if (options + option_len > (__u8 *)data_end)
		return TC_ACT_OK;
	if (option_len && has_guard_option(options, option_len))
		return TC_ACT_OK;

	return TC_ACT_SHOT;
}

SEC("classifier")
int rst_guard(struct __sk_buff *skb)
{
	void *data = (void *)(long)skb->data;
	void *data_end = (void *)(long)skb->data_end;
	struct ethhdr *eth = data;
	__u16 protocol;
	__u32 offset = sizeof(*eth);

	if ((void *)(eth + 1) > data_end)
		return TC_ACT_OK;
	protocol = eth->h_proto;
	if (protocol == BPF_HTONS(ETH_P_8021Q) ||
	    protocol == BPF_HTONS(ETH_P_8021AD)) {
		struct vlan_header *vlan = data + offset;
		if ((void *)(vlan + 1) > data_end)
			return TC_ACT_OK;
		protocol = vlan->encapsulated_proto;
		offset += sizeof(*vlan);
	}

	if (protocol == BPF_HTONS(ETH_P_IP)) {
		struct iphdr *ip = data + offset;
		__u32 ihl;
		if ((void *)(ip + 1) > data_end)
			return TC_ACT_OK;
		ihl = (__u32)ip->ihl * 4;
		if (ip->protocol != IPPROTO_TCP || ihl < sizeof(*ip) ||
			data + offset + ihl > data_end)
			return TC_ACT_OK;
		return check_tcp(data, data_end, offset + ihl);
	}

	if (protocol == BPF_HTONS(ETH_P_IPV6)) {
		struct ipv6hdr *ip6 = data + offset;
		if ((void *)(ip6 + 1) > data_end || ip6->nexthdr != IPPROTO_TCP)
			return TC_ACT_OK;
		return check_tcp(data, data_end, offset + sizeof(*ip6));
	}

	return TC_ACT_OK;
}

/*
 * Client-side companion.  TC egress sees RSTs generated by the local TCP
 * stack.  For a header-only IPv4 RST, make room at the network header,
 * move the IP/TCP headers back, and use the new room as TCP options.
 */
SEC("classifier/egress")
int rst_guard_client_egress(struct __sk_buff *skb)
{
	void *data = (void *)(long)skb->data;
	void *data_end = (void *)(long)skb->data_end;
	struct ethhdr *eth = data;
	struct iphdr *ip;
	struct tcphdr *tcp;
	__u32 ip_offset = sizeof(*eth);
	__u32 ihl;
	__u32 tcp_offset;
	__u32 tcp_len;
	__u16 old_total;
	__u16 old_offset_flags;
	__u16 old_doff_flags;
	__u16 new_doff_flags;
	__u16 new_total;
	__u8 option[12] = {
		TCP_OPT_EXPERIMENTAL, RST_GUARD_OPTION_LEN,
		0x52, 0x53, 0x54, 0x47, 0x55, 0x41, 0x52, 0x44,
		0x00, 0x00,
	};

	if ((void *)(eth + 1) > data_end || eth->h_proto != BPF_HTONS(ETH_P_IP))
		return TC_ACT_OK;
	ip = data + ip_offset;
	if ((void *)(ip + 1) > data_end || ip->protocol != IPPROTO_TCP)
		return TC_ACT_OK;
	ihl = (__u32)ip->ihl * 4;
	if (ihl < sizeof(*ip) || ip_offset + ihl > (__u64)(data_end - data))
		return TC_ACT_OK;
	tcp_offset = ip_offset + ihl;
	tcp = data + tcp_offset;
	if ((void *)(tcp + 1) > data_end ||
		(tcp->source != BPF_HTONS(SSH_PORT) &&
		 tcp->dest != BPF_HTONS(SSH_PORT)) || !tcp->rst)
		return TC_ACT_OK;
	tcp_len = (__u32)tcp->doff * 4;
	if (tcp_len < sizeof(*tcp) || tcp_len > 48 ||
		tcp_offset + tcp_len > (__u64)(data_end - data))
		return TC_ACT_OK;
	if (ip->tot_len != BPF_HTONS(ip_offset + ihl + tcp_len - ip_offset))
		return TC_ACT_OK; /* Do not touch fragmented/GSO-like packets. */
	if (has_guard_option((__u8 *)tcp + sizeof(*tcp),
				     tcp_len - sizeof(*tcp)))
		return TC_ACT_OK;

	old_total = ip->tot_len;
	old_offset_flags = *(__u16 *)((__u8 *)tcp + 12);
	new_doff_flags = old_offset_flags | BPF_HTONS(3 << 12);
	old_doff_flags = old_offset_flags;
	if (bpf_skb_adjust_room(skb, sizeof(option), BPF_ADJ_ROOM_NET,
				BPF_F_ADJ_ROOM_NO_CSUM_RESET))
		return TC_ACT_OK;

	/* The helper inserted room before the old IP header; restore headers. */
	for (int i = 0; i < 60; i++) {
		__u8 byte;
		if (i >= ihl)
			break;
		if (bpf_skb_load_bytes(skb, ip_offset + sizeof(option) + i,
					       &byte, sizeof(byte)) < 0 ||
		    bpf_skb_store_bytes(skb, ip_offset + i, &byte, sizeof(byte), 0) < 0)
			return TC_ACT_OK;
	}
	for (int i = 0; i < 60; i++) {
		__u8 byte;
		if (i >= tcp_len)
			break;
		if (bpf_skb_load_bytes(skb, tcp_offset + sizeof(option) + i,
					       &byte, sizeof(byte)) < 0 ||
		    bpf_skb_store_bytes(skb, tcp_offset + i, &byte, sizeof(byte), 0) < 0)
			return TC_ACT_OK;
	}

	new_total = old_total + BPF_HTONS(sizeof(option));
	new_doff_flags = (old_doff_flags & BPF_HTONS(0x0fff)) |
			 BPF_HTONS(3 << 12);
	if (bpf_l3_csum_replace(skb, ip_offset + offsetof(struct iphdr, check),
				old_total, new_total, sizeof(old_total)) < 0 ||
	    bpf_l4_csum_replace(skb, tcp_offset + 12, old_doff_flags,
				new_doff_flags, sizeof(old_doff_flags)) < 0)
		return TC_ACT_OK;
	if (bpf_skb_store_bytes(skb, ip_offset + offsetof(struct iphdr, tot_len),
				&new_total, sizeof(new_total), 0) < 0 ||
	    bpf_skb_store_bytes(skb, tcp_offset + 12, &new_doff_flags,
				 sizeof(new_doff_flags), 0) < 0)
		return TC_ACT_OK;
	for (int i = 0; i < sizeof(option) / sizeof(__u16); i++) {
		__u16 word = BPF_HTONS(((__u16)option[i * 2] << 8) |
					option[i * 2 + 1]);
		if (bpf_l4_csum_replace(skb, tcp_offset + offsetof(struct tcphdr, check),
					0, word, sizeof(word)) < 0)
			return TC_ACT_OK;
	}
	if (bpf_skb_store_bytes(skb, tcp_offset + tcp_len, option,
				 sizeof(option), 0) < 0)
		return TC_ACT_OK;
	return TC_ACT_OK;
}

char LICENSE[] SEC("license") = "GPL";
